## Import Data

In [2]:
import pandas as pd
import numpy as np
from scipy import stats
# import statsmodels.api as sm
# import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns
from pathlib import Path

In [ ]:
# PATH SETUP
BASE_DIR = Path.cwd().parent 
DATA_DIR = BASE_DIR / "01_Databases"
OUTPUT_DIR = BASE_DIR / "05_Deliverables"


# --- DISPLAY SETTINGS ---
    # pd.options.display.max_columns = None 


# --- IMPORT & EXPORT DATA ---
    # df = pd.read_csv(DATA_DIR / "data.csv")
    # df.to_csv(OUTPUT_DIR / "cleaned_data.csv", index=False)
    # df.to_excel(OUTPUT_DIR / "cleaned_data.xlsx", index=False)


# --- DATAFRAME INSPECTION  ---
df.shape
df.head()
df.tail()
df.info()
df.describe()
df.shape
df.dtypes
df.size 
df[''column_name''].unique() # Get unique values in a column
df["column_name"].value_counts() # Get counts of unique values in a column
df.columns # if df.columns = [''column1', 'column2'] it will rename the columns to column1 and column2.
df.isnull().sum() # Get the number of missing values in each column
    # df.loc['something'] # Access a row by label. If df.loc['a':'k', ['column1', 'column2']] it will access rows from a to k and columns column1 and column2.
    # df.iloc[0] # Access a row by integer position. If df.loc[:5, ['column1', 'column2']] it will access rows from 0 to 5 and columns column1 and column2.
    # df["column_name"] # Access a column by name
    # df["column_name"].unique() # Get unique values in a column
    # df["column_name"].value_counts() # Get counts of unique values in a column
    # df.sort_values('column1', ascending=False) # Sorts the DataFrame by a specific column in descending order.


# --- DATA CLEANING ---
    # df.drop(columns=["unnecessary_column"], inplace=True)
    # df.drop (columns=["unnecessary_column1", "unnecessary_column2"], inplace=True)
    # df.dropna(inplace=True)
    # df.dropna(axis=1, inplace=True) # Drop columns with missing values
    # df.dropna(how="all", inplace=True) # only drop rows with all columns with missing values
    # df.dropna(thresh=2, inplace=True) # only drop rows with at least 2 non-missing values

    # df.fillna(df.mean(), inplace=True)
    #df.dillna (method="ffill", inplace=True) # Forward fill: fills missing values with the last non-missing value.
    # df.fillna(method="bfill", inplace=True) # Backward fill: fills missing values with the next non-missing value. 
    #                                           axis=0 for filling in the direction of columns, axis=1 for direction of rows.

    # df["category"] = df["category"].astype("category") # Convert a column to a categorical data type, 
    #                                                       which can save memory and improve performance when working with categorical data.

    # df.duplicated() # Check for duplicate rows in the DataFrame. It returns a boolean Series where True indicates a duplicate row.
    # df.duplicated(keep='first') # Keep the first occurrence of each duplicate row or 'last' to keep the last occurrence. If keep=False, it marks all duplicates as True.
    # df.drop_duplicates(inplace=True) # Remove duplicate rows from the DataFrame. By default, it keeps the first occurrence of each duplicate row and drops the rest. You can specify keep='
    
    # df ["column_name"].str.strip('_', expand=True) # Remove leading and trailing whitespace from a string column, and if expand=True it will split the string into multiple columns 
                                                       # based on the specified separator (in this case, an underscore).
    # df["column_name"].str.split("_") # Split a string column into multiple columns
    # df["column_name"].str.lower() # Convert all characters in a string column to lowercase.
    # df["column_name"].str.upper() # Convert all characters in a string column to uppercase.
    # df["column_name"].str.replace("old_value", "new_value") # Replace occurrences of a specified value in a string column with a new value.
    # df["column_name"].str.contains("search_term") # Check if a string column contains a specific term or pattern.

    # OUTLIERS
    # Outliers can be detected using the IQR method, Z-score method, or visualizations like box plots. Once identified, outliers can be handled by removing them, capping them, or transforming the data.
    # For example, using the IQR method:
    # Q1 = df["variable"].quantile(0.25)
    # Q3 = df["variable"].quantile(0.75)
    # IQR = Q3 - Q1
    # lower_bound = Q1 - 1.5 * IQR
    # upper_bound = Q3 + 1.5 * IQR
    # df = df[(df["variable"] >= lower_bound) & (df["variable"] <= upper_bound)] # This will keep only the rows where the variable is within the lower and upper bounds, effectively removing outliers.


# --- DATA MANIPULATION ---
    # df.groupby("category").mean()
    # df.pivot_table(index="category", values="variable", aggfunc="mean")
    # df["new_column"] = df["variable1"] * df["variable2"]
    # The below examples explain what they do. They are not meant to be used together.
    # df["new_column"] = df["variable"].apply(lambda x: x * 2) # Applies a function to each element in the "variable" column, creating a new column with the results.
    # df["new_column"] = df["variable"].map(lambda x: x * 2) # Similar to apply, but map is typically used for mapping values in a Series according to an input correspondence (like a dictionary) or applying a function element-wise. It can also be used to map values from one set to another, such as mapping categorical values to numerical values.

# --- DATA VISUALIZATION  --- (examples with marplotlib)
    # Distribution plot with x axis type, title. Data displayed as a line.
    # p1 = figure(x_axis_type="datetime", title="Time Series Plot", plot_height=300, plot_width=800)
    # p1.line(df.index, df["variable"], line_width=2)
    # show(p1)

    # histogram
    # plt.hist(df["variable"], bins=30)
    # plt.title("Distribution of Variable")
    # plt.xlabel("Variable")
    # plt.ylabel("Frequency")

    # scatter plot
    # plt.scatter(df["variable1"], df["variable2"])
    # plt.title("Variable1 vs Variable2")    
    # plt.xlabel("Variable1")
    # plt.ylabel("Variable2")

    # box plot
    # plt.boxplot(df["variable"])
    # plt.title("Distribution of Variable")
    # plt.xlabel("Variable")
    # plt.ylabel("Value")

    # bar plot
    # plt.bar(df["category"], df["variable"])
    # plt.title("Variable by Category")
    # plt.xlabel("Category")
    # plt.ylabel("Variable")


# --- DATA ANALYSIS ---
    # correlation_matrix = df.corr()
    # t_stat, p_value = stats.ttest_ind(df["group1"], df["group2"])
    # model = smf.ols("dependent ~ independent1 + independent2", data=df).fit()

## Python Theory Summary Notebook

### Numpy

In [12]:
# --- NumPy ---
    # Base Library for numerical computing, providing support for arrays, matrices, and mathematical functions. 
    # It's used as a base for many other libraries, including pandas and scikit-learn.
    # Numpy Array: 
Array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Array.shape
Array.dtype
# Indexing and Matrices
Array[:,1] # Accessing the second column of the array (rows, index 1)
Array[0,2]= 99 # Accesses a specific element, and when assigning equality, it assigns a new value
Array

array([[ 1,  2, 99],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
# Summary statistics. Calculating several summary statistics for the array, including mean, median, standard deviation, and correlation coefficient.
sum_value = Array.sum(axis=0) # Sum of each column, in this case the axis.
mean_value = Array.mean()
median_value = np.median(Array)
std_value = Array.std()
correlation = np.corrcoef(Array)
variation = Array.var()

In [ ]:
# Broadcasting and Vectorized Operations:
# Broadcasting allows you to perform operations on arrays of different shapes and sizes without explicitly reshaping them
# We can apply a function or a mathematical operation to an entire array without needing to loop through each element.
Array + 10 # Adds 10 to each element in the array
Array * 2 # Multiplies each element in the array by 2. Same to divide / or subtract and so on.
# In this case we are saying that if we have an array called b that is (10, 10, 10), to sum it to our Array would correspond to just suming + 10 directly.

In [16]:
a = np.arange(5)
a + 20

array([20, 21, 22, 23, 24])

In [17]:
# Bollean arrays
# Boolean arrays are used to select specific elements from an array based on a condition.
# They are created by comparing two arrays element-wise using comparison operators like ==, >, <, etc.
Array > 5 # This will return a boolean array where each element is True if the condition is met and False otherwise.

array([[False, False,  True],
       [False, False,  True],
       [ True,  True,  True]])

In [18]:
Array[Array > 5] # This will return the values of the array where the boolean array is True

array([99,  6,  7,  8,  9])

In [19]:
# Bollean operators. They are used to impose conditions on the array. The operators are: & (and), | (or), ~ (not).
# For example, we can use the & operator to combine multiple conditions: 
Array[~(Array > 5)]  # values not greater than 5
Array[(Array < 3) | (Array > 7)]  # values less than 3 or greater than 7
Array[(Array > 2) & (Array < 9)]  # values greater than 2 and less than 9

array([4, 5, 6, 7, 8])

In [32]:
# Useful functions

# Sorting and Returning.
np.unique(Array) # Returns the unique values in the array
np.sort(Array) # Sorts the array
np.argmax(Array) # Returns the index of the maximum value in the array
np.argmin(Array) # Returns the index of the minimum value in the array

# Generating random numbers or queries
np.random.random(size=(3, 3)) # Generates a 3x3 array of random numbers between 0 and 1
np.random.randint(0, 10, size=(3, 3)) # Generates a 3x3 array of random integers between 0 and 10
np.random.normal(loc=0, scale=1, size=(3, 3)) # Generates a 3x3 array of random numbers from a normal distribution with mean 0 and standard deviation 1
np.random.normal(size=5) # Generates a 1D array of 5 random numbers from a normal distribution with mean 0 and standard deviation 1
np.random.choice([1, 2, 3, 4, 5], size=1) # Generates a 1D array of 1 random numbers from a normal distribution with mean 0 and standard deviation 1

# Arange and Linspace
np.arange(0, 10, 2) # Generates an array of values from 0 to 10 with a step of 2
np.linspace(0, 10, 5) # Generates an array of 5 evenly spaced values from 0 to 10

# Reshaping and Transposing
np.arange(10).reshape(2, 5) # Reshapes a 1D array of 10 elements into a 2D array with 2 rows and 5 columns

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Pandas

In [ ]:
# Pandas is the library for data manipulation and analysis, providing data structures like DataFrames and Series, as well as powerful tools for handling and analyzing data.
# It's built on top of NumPy and provides more advanced data manipulation capabilities, such as handling missing data, grouping, and merging datasets.
# It's the most important library for DA.

# Series: Indexing and Selection. The Series is a one-dimensional array-like object that can hold any data type. It has an index that allows for easy selection and manipulation of data.
s = pd.Series([10, 20, 30, 40, 50], index=["a", "b", "c", "d", "e"])
s["a"] # Accessing the value at index "a"
s[0] # Accessing the value at index 0. In this case it doesn't exist, therefor we should use iloc to access it.
s.iloc[0] # Accessing the value at index 0 using iloc
# or selecting a range
s.iloc[0:3] # Accessing the values from index 0 to 2 using iloc

#It also exist loc. The difference is that loc is label-based, while iloc is integer position-based. So, if we want to access the value at index "a" using loc, we would use s.loc["a"].
# df.loc[row_label, col_label] selects by row and column labels.

s["a"] = 100 # Modifying the value at index "a"
s[0] = 100 # Modifying the value at index 0

# Bollean operations or Bollean Series. It works similar to NumPy bollean arrays, but with the added functionality of the index. We can use boolean indexing to select specific values from the Series based on a condition.
s > 30 # This will return a boolean Series where each element is True if the condition is met and False otherwise.
s[s > 30] # This will return the values of the Series where the boolean Series is True.
# Operators apply the same way to Series and in Numpy, we can use & (and), | (or), ~ (not) to combine multiple conditions.
s[~(s > 30)]  # values not greater than 30
s[(s < 30) | (s > 70)]  # values less than 30 or greater than 70
# The same as assigning new values.
s[s > 30] = 200 # All values bigger than 30 were  assigned the value 200.


In [ ]:
# DataFrame: Indexing and Selection. The DataFrame is a two-dimensional array-like object that can hold any data type. It has both row and column indices, allowing for more complex data manipulation and analysis.
df = pd.DataFrame({
    "column1": [1, 2, 3, 4, 5],
    "column2": ["a", "b", "c", "d", "e"] 
   # df.loc['something'] # Access a row by label. If df.loc['a':'k', ['column1', 'column2']] it will access rows from a to k and columns column1 and column2.
    # df.iloc[0] # Access a row by integer position. If df.loc[:5, ['column1', 'column2']] it will access rows from 0 to 5 and columns column1 and column2.
    # df["column_name"] # Access a column by name
    # df["column_name"].unique() # Get unique values in a column
    # df["column_name"].value_counts() # Get counts of unique values in a column

# Selecting rows that meet conditions. We can use boolean indexing to select specific rows from the DataFrame based on a condition.
df["column1"] > 3 # This will return a boolean Series where each element is True if the condition is met and False otherwise.
df.loc[df["column1"] > 3] # will return the rows of the DataFrame where the condition is met, in this case where column1 is greater than 3. It will also return all the other columns.

df.rename(columns={"column1": "new_column1", "column2": "new_column2"}, inplace=True) # Renames columns in the DataFrame. The inplace=True argument modifies the original DataFrame instead of creating a new one.

# Creating columns.
df['new_column'] = df['old_column']/df['another_column'] * 2 # Creates a new column by multiplying the values of an existing column by 2.
#Statistical information about the DataFrame.
df.describe() # Provides summary statistics for the DataFrame, including count, mean, standard deviation, min, max, and quartiles for each numeric column.

# Sorting rows or columns.
df.sort_values('column1') # Sorts the DataFrame by a specific column in ascending order.
df.sort_values('column1', ascending=False) # Sorts the DataFrame by a specific column in descending order.
df.sort_values(['column1', 'column2']) # Sorts the DataFrame by multiple columns in ascending order.